#
# Main Configuration - KanyeMod
#

# Server
server:

  # Server Name
  name: KanyeCraft

  # Executives
  executives: []

  # Owner(s)
  owners: []

# Command and Chat Formats
formats:

  # Simple Chat Format
  chat: '%display%&7: &f%message%'

  # AdminChat Format
  admin: '[&bADMIN&f] &4%name% %tagcolor%[%tag%]&f: &b%message%'