#
# Main Configuration - KanyeMod
#

# Server
server:

  # Server Name
  name: KanyeCraft

  # Server MOTD
  motd: '&5KanyeCraft &8- &5Spigot 1.12.2'

  # Executives
  executives: []

  # Owner(s)
  owners: []

# Command and Chat Formats
formats:

  # Public Chat Format
  chat: '%display%&7: &f%message%'

  # Default AdminChat Format
  admin: '[&bADMIN&f] &4%name% %tagcolor%[%tag%]&f: &b%message%'

  # /say Format
  say: '&d[Server:%name%] %message%'